
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.ServerSocket;
import java.net.Socket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sirak
 */
public class Client extends javax.swing.JFrame {
   

    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    // FileReader filereader;

   public Client() {
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        test_txt = new javax.swing.JTextField();
        vaka_txt = new javax.swing.JTextField();
        ölü_txt = new javax.swing.JTextField();
        yogunbakim_txt = new javax.swing.JTextField();
        entübe_txt = new javax.swing.JTextField();
        iyilesen_txt = new javax.swing.JTextField();
        bugun_test = new javax.swing.JTextField();
        bugun_vaka = new javax.swing.JTextField();
        bugun_vefat = new javax.swing.JTextField();
        bugun_iyilesen = new javax.swing.JTextField();
        tarih_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                 TÜRKİYE GÜNLÜK KORANAVİRÜS TABLOSU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("TOPLAM TEST SAYISI");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("TOPLAM VAKA SAYISI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("TOPLAM VEFAT SAYIMIZ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TOPLAM YOĞUN BAKIM ");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("TOPLAM ENTÜBE SAYISI");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("TOPLAM İYİLESEN");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("HASTA SAYISI");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("HASTA SAYISI");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("BUGÜNKİ TEST SAYISI");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("BUGÜNKİ VAKA SAYISI");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("BUGÜNKİ VEFAT SAYISI");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("BUGÜNKİ İYİLEŞEN SAYISI");

        test_txt.setBackground(new java.awt.Color(0, 153, 153));
        test_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        test_txt.setForeground(new java.awt.Color(255, 255, 255));
        test_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_txtActionPerformed(evt);
            }
        });

        vaka_txt.setBackground(new java.awt.Color(0, 153, 153));
        vaka_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        vaka_txt.setForeground(new java.awt.Color(255, 255, 255));
        vaka_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaka_txtActionPerformed(evt);
            }
        });

        ölü_txt.setBackground(new java.awt.Color(0, 153, 153));
        ölü_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ölü_txt.setForeground(new java.awt.Color(255, 255, 255));
        ölü_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ölü_txtActionPerformed(evt);
            }
        });

        yogunbakim_txt.setBackground(new java.awt.Color(0, 153, 153));
        yogunbakim_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        yogunbakim_txt.setForeground(new java.awt.Color(255, 255, 255));
        yogunbakim_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yogunbakim_txtActionPerformed(evt);
            }
        });

        entübe_txt.setBackground(new java.awt.Color(0, 153, 153));
        entübe_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        entübe_txt.setForeground(new java.awt.Color(255, 255, 255));
        entübe_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entübe_txtActionPerformed(evt);
            }
        });

        iyilesen_txt.setBackground(new java.awt.Color(0, 153, 153));
        iyilesen_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        iyilesen_txt.setForeground(new java.awt.Color(255, 255, 255));
        iyilesen_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iyilesen_txtActionPerformed(evt);
            }
        });

        bugun_test.setEditable(false);
        bugun_test.setBackground(new java.awt.Color(0, 102, 102));
        bugun_test.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        bugun_test.setForeground(new java.awt.Color(255, 255, 255));
        bugun_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugun_testActionPerformed(evt);
            }
        });

        bugun_vaka.setBackground(new java.awt.Color(0, 153, 153));
        bugun_vaka.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        bugun_vaka.setForeground(new java.awt.Color(255, 255, 255));
        bugun_vaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugun_vakaActionPerformed(evt);
            }
        });

        bugun_vefat.setBackground(new java.awt.Color(0, 102, 102));
        bugun_vefat.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        bugun_vefat.setForeground(new java.awt.Color(255, 255, 255));
        bugun_vefat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugun_vefatActionPerformed(evt);
            }
        });

        bugun_iyilesen.setBackground(new java.awt.Color(0, 153, 153));
        bugun_iyilesen.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        bugun_iyilesen.setForeground(new java.awt.Color(255, 255, 255));
        bugun_iyilesen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugun_iyilesenActionPerformed(evt);
            }
        });

        tarih_txt.setBackground(new java.awt.Color(0, 153, 153));
        tarih_txt.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        tarih_txt.setForeground(new java.awt.Color(255, 255, 255));
        tarih_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarih_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 186, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel11))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iyilesen_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(test_txt)
                    .addComponent(vaka_txt)
                    .addComponent(ölü_txt)
                    .addComponent(yogunbakim_txt)
                    .addComponent(entübe_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tarih_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bugun_test, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(bugun_vaka)
                            .addComponent(bugun_vefat)
                            .addComponent(bugun_iyilesen))
                        .addGap(109, 109, 109))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(test_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(vaka_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(tarih_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ölü_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(21, 21, 21))
                            .addComponent(yogunbakim_txt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel14)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bugun_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bugun_vaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(bugun_vefat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bugun_iyilesen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entübe_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iyilesen_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.getAccessibleContext().setAccessibleName("TOPLAM YOĞUN BAKIM\n HASTA SAYISI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void test_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_txtActionPerformed

        try {
            // serverdan yeni eklenen değerlerin güncel bir şekilde gelmesi için dosya okua işlemini yapması gerekir .
            //dosya okunurken entera basılınca veriler geliyor. o kısmı düzeltemedim.
            
           /* burada singleton aktif edebilmek için 
            Singleton a=Singleton.getInstance();  yeni bir nesne oluşturmamak için new anahtar kelimesini kullanmamak için burada singleton classımız çağırmalıyız. 
     
           a.reader(); */
            
            
            FileReader f = new FileReader("C:\\Users\\Public\\corona.txt");
            BufferedReader in = new BufferedReader(f);
            String[] line = new String[2];

            for (int i = 0; i < 12; i++) {
                switch (i) {
                    case 1:
                        line[i] = in.readLine();
                
                        System.out.println(line[i]);
                        test_txt.setText(line[i]);

                    case 2:
                        line[i] = in.readLine();
                     
                        System.out.println(line[i]);
                        vaka_txt.setText(line[i]);

                    case 3:
                        line[i] = in.readLine();

                     
                        System.out.println(line[i]);
                        ölü_txt.setText(line[i]);
                    case 4:
                        line[i] = in.readLine();

                     
                        System.out.println(line[i]);
                        yogunbakim_txt.setText(line[i]);
                    case 5:
                        line[i] = in.readLine();

                     
                        System.out.println(line[i]);
                        entübe_txt.setText(line[i]);

                    case 6:
                        line[i] = in.readLine();

                       
                        System.out.println(line[i]);
                        iyilesen_txt.setText(line[i]);

                    case 7:
                        line[i] = in.readLine();

                      
                        System.out.println(line[i]);
                        tarih_txt.setText(line[i]);
                    case 8:
                        line[i] = in.readLine();

                      
                        System.out.println(line[i]);
                        bugun_test.setText(line[i]);
                    case 9:
                        line[i] = in.readLine();

                       
                        System.out.println(line[i]);
                        bugun_vaka.setText(line[i]);
                    case 10:
                        line[i] = in.readLine();

                   
                        System.out.println(line[i]);
                        bugun_vefat.setText(line[i]);
                    case 11:
                        line[i] = in.readLine();

               
                        System.out.println(line[i]);
                        bugun_iyilesen.setText(line[i]);
                        break;
                }
            }
        } // }
        catch (Exception e) {
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_test_txtActionPerformed

    private void vaka_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaka_txtActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_vaka_txtActionPerformed

    private void ölü_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ölü_txtActionPerformed


    }//GEN-LAST:event_ölü_txtActionPerformed

    private void yogunbakim_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yogunbakim_txtActionPerformed


    }//GEN-LAST:event_yogunbakim_txtActionPerformed

    private void entübe_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entübe_txtActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_entübe_txtActionPerformed

    private void iyilesen_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iyilesen_txtActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_iyilesen_txtActionPerformed

    private void bugun_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugun_testActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_bugun_testActionPerformed

    private void tarih_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarih_txtActionPerformed


    }//GEN-LAST:event_tarih_txtActionPerformed

    private void bugun_vakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugun_vakaActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_bugun_vakaActionPerformed

    private void bugun_vefatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugun_vefatActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_bugun_vefatActionPerformed

    private void bugun_iyilesenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugun_iyilesenActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_bugun_iyilesenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Singleton a=Singleton.getInstance(); 
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
                // Singleton singleton =Singleton.GetInstance();

            }
          
    

        });
        


        String test_in = "";
        String vaka_in = "";
        String yogunbakim_in = "";
        String entübe_in = "";
        String vefat_in = "";
        String iyilesen_in = "";
        String tarih_in = "";
        String bugun_testin = "";
        String bugun_vakain = "";
        String bugun_vefatin = "";
        String bugun_iyilesenin = "";


        try {
          
            
             s = new Socket("127.0.0.1", 1101);
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());

            test_in = din.readUTF();
            test_txt.setText(test_txt.getText().trim() + "" + test_in);
            vaka_in = din.readUTF();
            vaka_txt.setText(vaka_txt.getText().trim() + "\n" + vaka_in);
            vefat_in = din.readUTF();
            ölü_txt.setText(ölü_txt.getText().trim() + "" + vefat_in);
            yogunbakim_in = din.readUTF();
            yogunbakim_txt.setText(yogunbakim_txt.getText().trim() + "" + yogunbakim_in);

            entübe_in = din.readUTF();
            entübe_txt.setText(entübe_txt.getText().trim() + "" + entübe_in);
            iyilesen_in = din.readUTF();
            iyilesen_txt.setText(iyilesen_txt.getText().trim() + "" + iyilesen_in);
            tarih_in = din.readUTF();
            tarih_txt.setText(tarih_txt.getText().trim() + "" + tarih_in);

            bugun_testin = din.readUTF();
            bugun_test.setText(bugun_test.getText().trim() + "" + bugun_testin);
            bugun_vakain = din.readUTF();
            bugun_vaka.setText(bugun_vaka.getText().trim() + "" + bugun_vakain);
            bugun_vefatin = din.readUTF();
            bugun_vefat.setText(bugun_vefat.getText().trim() + "" + bugun_vefatin);
            bugun_iyilesenin = din.readUTF();
            bugun_iyilesen.setText(bugun_iyilesen.getText().trim() + "" + bugun_iyilesenin);

        } catch (Exception e) {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField bugun_iyilesen;
    private static javax.swing.JTextField bugun_test;
    private static javax.swing.JTextField bugun_vaka;
    private static javax.swing.JTextField bugun_vefat;
    private static javax.swing.JTextField entübe_txt;
    private static javax.swing.JTextField iyilesen_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private static javax.swing.JTextField tarih_txt;
    private static javax.swing.JTextField test_txt;
    private static javax.swing.JTextField vaka_txt;
    private static javax.swing.JTextField yogunbakim_txt;
    private static javax.swing.JTextField ölü_txt;
    // End of variables declaration//GEN-END:variables
}
